### ISSUE TITLE
PRs go live before merge

### ISSUE THREAD

**Issue by tomarken** [ItsiW/VILF#15]
On my last PR I noticed that VILF displayed my review as soon as it finished running the CI job to test the build. I believe this was changed when I made the CLI interface so that we could test changes to commands used to build VILF. Specifically, I added
```
  pull_request:
    branches: [ develop ]
```
to `deploy.yaml`. Is this the intended outcome? If not, maybe we should change this so that for PRs we just run up to `./vilf build` but don't run these lines?
```
    - uses: google-github-actions/auth@v0
      with:
        credentials_json: "${{ secrets.CLIMAX_VILF_SA_KEY }}"
    - uses: google-github-actions/setup-gcloud@v0
    - run: gsutil -m rsync -R build gs://climax-vilf-bucket
```
